# Generated by Django 5.2.6 on 2025-09-24 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='user.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='pending', max_length=10)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_trades', to='user.user')),
                ('proposer_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_proposer_book', to='user.book')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='user.user')),
                ('receiver_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_as_receiver_book', to='user.book')),
            ],
            options={
                'verbose_name': 'Troca',
                'verbose_name_plural': 'Trocas',
            },
        ),
    ]
